import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { dashboardFixture, mountDashboard } from "./dashboard-fixture";

for (const width of [390, 1440]) {
  test(`log console scopes sources, searches literal text and exports clean logs at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 1000 });
    await page.addInitScript(() => {
      Object.defineProperty(navigator, "clipboard", { value: { writeText: async (value: string) => Object.assign(window, { copiedLogs: value }) }, configurable: true });
    });
    const data = dashboardFixture();
    const first = data.projects[0];
    first.runtime.phase = "running"; first.runtime.worktreePath = first.worktrees[0].path; first.runtime.startedAt = "2026-09-13T12:00:00Z";
    first.runtime.logs = ["\u001b[31mERROR one\u001b[0m", "context line", "error two", "literal [a].*", "<script>window.injected=true</script>", "long " + "x".repeat(3000)];
    const other = structuredClone(first); other.project.id = "api"; other.project.name = "Fixture API"; other.runtime.phase = "stopped"; other.runtime.logs = ["older-api-output", "error api"];
    data.projects.push(other);
    const { requests, errors } = await mountDashboard(page, data);
    await page.getByRole("combobox", { name: /Choose project/ }).click();
    await page.getByRole("option", { name: /All projects/ }).click();
    if (width < 768) await page.getByRole("button", { name: "Toggle navigation", exact: true }).click();
    await page.getByRole("navigation").getByRole("button", { name: "Logs", exact: true }).click();
    const screen = page.locator("[data-logs-dashboard]");
    const console = page.locator('[data-log-console][data-project-id="web"]');
    const otherConsole = page.locator('[data-log-console][data-project-id="api"]');
    const search = screen.getByRole("searchbox");
    await expect(page.locator("[data-log-console]")).toHaveCount(2);
    await expect(screen.getByRole("navigation")).toHaveCount(0);
    await expect(otherConsole.getByRole("button", { name: "Expand logs: Fixture API" })).toHaveAttribute("aria-expanded", "false");
    await expect(otherConsole.locator("[data-log-lines]")).toHaveCount(0);
    const text = console.locator("[data-log-lines]");
    await expect(console).toContainText("Current run");
    await expect(text).toContainText("ERROR one");
    expect(await text.textContent()).not.toContain("\u001b");
    expect(await page.evaluate(() => (window as unknown as { injected?: boolean }).injected)).toBeUndefined();
    await search.fill("error");
    await expect(console.locator("mark")).toHaveCount(2);
    await expect(otherConsole.locator("mark")).toHaveCount(1);
    await expect(otherConsole.getByRole("button", { name: "Collapse logs: Fixture API" })).toHaveAttribute("aria-expanded", "true");
    await expect(console.locator('[data-current-hit="true"]')).toHaveText("ERROR");
    await console.getByRole("button", { name: "Next match", exact: true }).click();
    await expect(console.locator('[data-current-hit="true"]')).toHaveText("error");
    await expect(text).toContainText("context line");
    await search.fill("[a].*");
    await expect(console.locator("mark")).toHaveCount(1);
    await console.getByRole("button", { name: "Copy displayed buffer", exact: true }).click();
    expect(await page.evaluate(() => (window as unknown as { copiedLogs: string }).copiedLogs)).toContain("ERROR one\ncontext line\nerror two");
    const downloadEvent = page.waitForEvent("download");
    await console.getByRole("button", { name: "Download displayed buffer", exact: true }).click();
    const download = await downloadEvent;
    expect(download.suggestedFilename()).toBe("Fixture-Web-logs.txt");
    expect(await readFile((await download.path())!, "utf8")).not.toContain("\u001b");
    await console.getByRole("button", { name: "Wrap lines", exact: true }).click();
    await expect(console.getByRole("button", { name: "Wrap lines", exact: true })).toHaveAttribute("aria-pressed", "false");
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await expect(otherConsole).toContainText("Last run logs");
    await expect(otherConsole.locator("[data-log-lines]")).toContainText("older-api-output");
    await expect(otherConsole.locator("[data-log-lines]")).not.toContainText("ERROR one");
    await search.fill("");
    await otherConsole.getByRole("button", { name: "Collapse logs: Fixture API" }).click();
    await expect(otherConsole.locator("[data-log-lines]")).toHaveCount(0);
    await otherConsole.getByRole("button", { name: "Expand logs: Fixture API" }).focus();
    await page.keyboard.press("Enter");
    await expect(otherConsole.locator("[data-log-lines]")).toBeVisible();
    await page.screenshot({ path: test.info().outputPath("logs.png"), fullPage: true, animations: "disabled" });
    await page.getByRole("combobox", { name: /Choose project/ }).click();
    await page.getByRole("option", { name: /Fixture Web/ }).click();
    await expect(page.locator("[data-log-console]")).toHaveCount(1);
    await expect(console.getByRole("button", { name: /Collapse logs|Expand logs/ })).toHaveCount(0);
    await expect(text).toContainText("ERROR one");
    await expect(console.getByRole("button", { name: "Start", exact: true })).toHaveCount(0);
    await page.getByRole("button", { name: "Switch language to Polish", exact: true }).click();
    await expect(screen.getByRole("searchbox", { name: "Szukaj w logach" })).toBeVisible();
    expect(requests).toEqual([]); expect(errors).toEqual([]);
  });
}

test("log reading pauses a rolling buffer and resumes at new output without adding subscriptions", async ({ page }) => {
  const data = dashboardFixture();
  const snapshot = data.projects[0];
  snapshot.runtime.phase = "running"; snapshot.runtime.startedAt = "2026-09-13T12:00:00Z"; snapshot.runtime.worktreePath = snapshot.worktrees[0].path;
  snapshot.runtime.logs = Array.from({ length: 400 }, (_, i) => `original-line-${i}`);
  const { errors } = await mountDashboard(page, data);
  await page.getByRole("navigation").getByRole("button", { name: "Logs", exact: true }).click();
  const console = page.locator("[data-log-console]");
  const viewport = console.getByRole("region", { name: "Log console" });
  const bottomDistance = () => viewport.evaluate((e) => e.scrollHeight - e.clientHeight - e.scrollTop);
  await expect.poll(bottomDistance).toBeLessThan(24);
  await viewport.evaluate((e) => { e.scrollTop = 0; });
  await expect(console.getByRole("button", { name: "Follow output", exact: true })).toBeVisible();
  snapshot.runtime.logs = [...snapshot.runtime.logs.slice(1), "new-line-at-the-end"];
  await page.evaluate(() => (window as unknown as { fixtureEvents: { emit: (type: string, data: unknown) => void } }).fixtureEvents.emit("changed", { kinds: ["runtime"], projectIds: ["web"] }));
  await expect(console.getByRole("button", { name: "New entries", exact: true })).toBeVisible();
  await expect(console.locator("[data-log-lines]")).not.toContainText("new-line-at-the-end");
  await expect(console.locator("[data-log-lines]")).toContainText("original-line-0");
  expect(await viewport.evaluate((e) => e.scrollTop)).toBe(0);
  await console.getByRole("button", { name: "New entries", exact: true }).click();
  await expect(console.locator("[data-log-lines]")).toContainText("new-line-at-the-end");
  await expect.poll(bottomDistance).toBeLessThan(24);
  await page.screenshot({ path: test.info().outputPath("logs-live.png"), animations: "disabled" });
  await page.getByRole("searchbox", { name: "Search logs" }).fill("not-present");
  await expect(console.getByRole("button", { name: "Next match" })).toBeDisabled();
  await expect(console.locator("[data-log-lines]")).toContainText("original-line-399");
  await expect.poll(() => page.evaluate(() => (window as unknown as { fixtureEvents: { active: number } }).fixtureEvents.active)).toBe(1);
  expect(errors).toEqual([]);
});
